name: PHP Tools

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tools:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install Composer dependencies
        run: composer install

      - name: updating composer
        run: composer update

      - name: updating phpmd
        run: composer update phpmd/phpmd pdepend/pdepend
        
      - name: Install PHP_CodeSniffer
        run: composer global require "squizlabs/php_codesniffer=*"

      - name: Add Composer Bin to PATH
        run: echo "$HOME/.composer/vendor/bin" >> $GITHUB_PATH

      - name: PHP lint
        run: php -l *.php

      - name: PHP Code Beautifier and Fixer (PHP CBF)
        run: phpcbf --standard=PSR12 *.php || true
        
      - name: PHP CodeSniffer (PHP CS)
        run: phpcs --standard=PSR12 *.php || true

      - name: PHP Mess Detector (PHPMD)
        run: phpmd *.php text cleancode


     
