name: PHP Tools

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tools:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install Composer dependencies
        run: composer install

      - name: updating composer
        run: composer update

      - name: updating cbf
        run: composer update squizlabs/php_codesniffer

      - name: updating phpmd
        run: composer update phpmd/phpmd pdepend/pdepend
        
      - name: updating cs
        run: composer require --dev squizlabs/php_codesniffer:"^3.6"

      - name: PHP lint
        run: php-l .

      - name: PHP Code Beautifier and Fixer (PHP CBF)
        run: phpcbf --standard=PSR12 .
        
      - name: PHP CodeSniffer (PHP CS)
        run: phpcs --standard=PSR12 .

      - name: PHP Mess Detector (PHPMD)
        run: phpmd . text cleancode


     
